### ISSUE TITLE
Regular newsletters

### ISSUE THREAD

**Issue by ghost** [mtcextendee/mautic-recurring-campaigns-bundle#1]
Hello there, Sorry this is not quite an 'issue'. Could you kindly explain what are the steps I need to follow if I want to send a newsletter every day/week? Thanks.

**Comment by kuzmany** [comment]
Maybe something  like this

![image](https://user-images.githubusercontent.com/462477/42324063-5c2f7bae-8062-11e8-9716-9473181e04a8.png)

You should test in your own way.

**Comment by ghost** [comment]
I wasn't sure whether clear logs on the same campaign or not. Many thanks! I have installed the plugin using composer and it's appearing under plugins folder. But it's not coming up under Plugins, ever after manually clearing the prod cache. Any tips?

**Comment by kuzmany** [comment]
Need click on button Install/Update plugins in right corner

**Comment by ghost** [comment]
Sorry what I meant earlier was even after clicking that button, it doesn't appear...
